services:

  db:
    build: ./database
    container_name: sentinel-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentinel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sentinel-net

  backend:
    build: ./backend
    container_name: sentinel-backend
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/sentinel
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - sentinel-net

volumes:
  postgres_data:

networks:
  sentinel-net:
    driver: bridge